name: Deploy deno-api-heroku to Heroku

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.4.6]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint deno-api-heroku
        run: deno fmt --check
      - name: Test deno-api-heroku
        run: .bin/test.sh

  deploy:
    runs-on: ubuntu-latest

    needs: test
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        env:
          HEROKU_USER: ${{ secrets.HEROKU_USER }}
          HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
        run: .bin/deploy.sh
